# Generated by Django 4.0.7 on 2023-03-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='eventcompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('event', models.CharField(max_length=150)),
                ('team', models.CharField(max_length=150)),
                ('budget', models.CharField(max_length=150)),
                ('number', models.CharField(max_length=150)),
                ('report', models.BooleanField(default=False)),
            ],
        ),
    ]
