# Generated by Django 4.0.7 on 2023-03-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourth', '0002_eventcompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcompany',
            name='Clients',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='eventcompany',
            name='Testimonals',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='eventcompany',
            name='services',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
