# Generated by Django 4.0.7 on 2023-03-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourth', '0003_eventcompany_clients_eventcompany_testimonals_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interiorcompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('Decorating', models.CharField(max_length=150)),
                ('services', models.CharField(max_length=150)),
                ('Testimonals', models.CharField(max_length=150)),
                ('Clients', models.CharField(max_length=150)),
                ('team', models.CharField(max_length=150)),
                ('budget', models.CharField(max_length=150)),
                ('number', models.CharField(max_length=150)),
                ('report', models.BooleanField(default=False)),
            ],
        ),
    ]
