# Generated by Django 4.0.7 on 2023-03-09 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fourth', '0004_interiorcompany'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcompany',
            name='Clients',
        ),
        migrations.RemoveField(
            model_name='eventcompany',
            name='Testimonals',
        ),
        migrations.RemoveField(
            model_name='eventcompany',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventcompany',
            name='services',
        ),
        migrations.RemoveField(
            model_name='eventcompany',
            name='team',
        ),
        migrations.RemoveField(
            model_name='interiorcompany',
            name='Clients',
        ),
        migrations.RemoveField(
            model_name='interiorcompany',
            name='Decorating',
        ),
        migrations.RemoveField(
            model_name='interiorcompany',
            name='Testimonals',
        ),
        migrations.RemoveField(
            model_name='interiorcompany',
            name='team',
        ),
    ]
