# Generated by Django 4.0.7 on 2023-03-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourth', '0005_remove_eventcompany_clients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcompany',
            name='employees',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='eventcompany',
            name='experience',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='eventcompany',
            name='services',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='eventcompany',
            name='specialized',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='interiorcompany',
            name='employees',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='interiorcompany',
            name='experience',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='interiorcompany',
            name='specialized',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
