# Generated by Django 4.0.7 on 2023-03-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('third', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('table', models.CharField(max_length=150)),
                ('drinks', models.CharField(max_length=150)),
                ('beverages', models.CharField(max_length=150)),
                ('Alcohol', models.CharField(max_length=150)),
                ('banquet', models.CharField(max_length=150)),
                ('food', models.CharField(max_length=150)),
                ('Decoration', models.CharField(max_length=150)),
                ('skirting', models.CharField(max_length=150)),
                ('rooms', models.CharField(max_length=150)),
            ],
        ),
    ]
