# Generated by Django 4.0.7 on 2023-03-04 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('third', '0003_interior'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Alcohol',
        ),
    ]
