# Generated by Django 4.0.7 on 2023-03-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('third', '0004_remove_event_alcohol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interior',
            name='dining',
        ),
        migrations.RemoveField(
            model_name='interior',
            name='kids',
        ),
        migrations.RemoveField(
            model_name='interior',
            name='kitchen',
        ),
        migrations.RemoveField(
            model_name='interior',
            name='living',
        ),
        migrations.RemoveField(
            model_name='interior',
            name='table',
        ),
        migrations.AddField(
            model_name='interior',
            name='Designs',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='interior',
            name='Tables',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='interior',
            name='boards',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='interior',
            name='others',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='interior',
            name='wallpapers',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='interior',
            name='woods',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
