# Generated by Django 4.0.7 on 2023-03-06 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('third', '0005_remove_interior_dining_remove_interior_kids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interior',
            name='quantity1',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='interior',
            name='quantity2',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='interior',
            name='quantity3',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='interior',
            name='quantity4',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='interior',
            name='quantity5',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='interior',
            name='quantity',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
