# Generated by Django 4.0.7 on 2023-03-06 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('third', '0007_interior_value'),
    ]

    operations = [
        migrations.DeleteModel(
            name='event',
        ),
    ]
