# Generated by Django 4.0.7 on 2023-03-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('third', '0009_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='report',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='interior',
            name='report',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
