# Generated by Django 4.0.7 on 2023-02-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('phonenumber', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=12)),
                ('country', models.CharField(max_length=12)),
                ('events', models.CharField(max_length=12)),
                ('food', models.CharField(max_length=12)),
                ('attendees', models.CharField(max_length=12)),
                ('date', models.CharField(max_length=12)),
                ('Time', models.CharField(max_length=12)),
                ('message', models.CharField(max_length=12)),
            ],
        ),
    ]
