# Generated by Django 4.0.7 on 2023-02-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='register1',
            name='report',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
