# Generated by Django 4.0.7 on 2023-02-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_register1_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='report',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
