# Generated by Django 4.0.7 on 2023-02-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_details_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='designing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('phonenumber', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=12)),
                ('country', models.CharField(max_length=12)),
                ('area', models.CharField(max_length=12)),
                ('budget', models.CharField(max_length=12)),
                ('message', models.CharField(max_length=12)),
                ('report', models.BooleanField(default=False)),
            ],
        ),
    ]
