# Generated by Django 4.0.7 on 2023-02-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0007_alter_designing_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='message',
            field=models.CharField(max_length=150),
        ),
    ]
