# Generated by Django 4.0.7 on 2023-03-03 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0011_details_alcohol_details_decoration_details_banquet_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='details',
        ),
    ]
