# Generated by Django 4.0.7 on 2023-03-03 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0013_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='Alcohol',
        ),
    ]
