# Generated by Django 4.0.7 on 2023-03-03 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0014_remove_detail_alcohol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='banquet',
        ),
    ]
