# Generated by Django 4.0.7 on 2023-03-04 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0015_remove_detail_banquet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='rooms',
        ),
    ]
