# Generated by Django 4.0.7 on 2023-03-06 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0017_remove_designing_electricity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='table',
        ),
    ]
