# Generated by Django 4.0.7 on 2023-03-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0018_remove_detail_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='skirting',
        ),
        migrations.AddField(
            model_name='detail',
            name='Budget',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
