# Generated by Django 4.0.7 on 2023-03-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0019_remove_detail_skirting_detail_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='events',
        ),
        migrations.AddField(
            model_name='detail',
            name='Events',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
