# Generated by Django 4.0.7 on 2023-03-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0020_remove_detail_events_detail_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='designing',
            name='Output',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='Output',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
