# Generated by Django 4.0.7 on 2023-03-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0021_designing_output_detail_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='Specialized',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
